### ISSUE TITLE
Just using SGCN

### ISSUE THREAD

**Issue by raziyev** [kdkalvik/ST-GCN#3]
Hello, Thank you for the great code.
I want to use just SGCN layer in my network. The first lines of code is like:

inputx = Input(shape=(3,64,25))
inputA = Input(shape=(1,25,25))
x, A = SGCN(1)([inputx,inputA])

but I get the below error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-07d86d81b323> in <module>()
      1 inputx = Input(shape=(3,64,25))
      2 inputA = Input(shape=(1,25,25))
----> 3 x, A = SGCN(1)([inputx,inputA])

4 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    668       except Exception as e:  # pylint:disable=broad-except
    669         if hasattr(e, 'ag_error_metadata'):
--> 670           raise e.ag_error_metadata.to_exception(e)
    671         else:
    672           raise

TypeError: in user code:

    TypeError: tf__call() missing 1 required positional argument: 'A'

Could you please tell me, what is wrong?

**Comment by itskalvik** [comment]
The graph adjacency matrix is [acquired from](https://github.com/kdkalvik/ST-GCN/blob/82d92a999ee91142647888db13b6c264f6fedc7c/model/stgcn.py#L131) the [Graph class](https://github.com/kdkalvik/ST-GCN/blob/82d92a999ee91142647888db13b6c264f6fedc7c/graph/ntu_rgb_d.py#L17). Please try defining your adjacency matrix in there.

**Comment by raziyev** [comment]
Thank you for answering.
Could you please tell me, how can I use SGCN, like as other Keras layers?

**Comment by itskalvik** [comment]
Oh, if you want to use the individual layers, you should do something like [this](https://github.com/kdkalvik/ST-GCN/blob/82d92a999ee91142647888db13b6c264f6fedc7c/model/stgcn.py#L140). The adjacency matrix is passed during the layer call.
